### PR TITLE
Remove creation date from generated PDFs

### PR DESCRIPTION
**Pull request by ericcornelissen**
... in order to prevent the PDFs from "changing" when running `npm run build` for new/updated SVGs.

The implementation is a bit of a hack as it involves providing a value for the `info.CreationDate` option that results in an empty string in the PDF.

Note that with this Pull Request, the change hasn't taken effect yet. The PDFs need to be regenerated once in order for the creation date to be set to an empty string, after which they will stay that way and unchanged SVGs no longer result in new PDFs.

### CODE REVIEW

**Review by adamrusted — APPROVED** [review]
This looks good to me, @ericcornelissen - and works perfectly when testing locally.
The only other proposal would be to set the creation date to the last time the SVG was modified on the main repo, but that's a headache for another PR!

**Comment by ericcornelissen** [comment]
> This looks good to me [...] and works perfectly when testing locally.

Thanks for verifying this :+1: 

> The only other proposal would be to set the creation date to the last time the SVG was modified on the main repo, but that's a headache for another PR!

I totally agree that would be a nicer solution, and I thought about it myself as well, but I can't think of a way to get this information currently (the file stats of the `npm install`ed SVGs does not contain the "real" last modified date) and I also don't think it makes sense to add a field for this to the `simple-icons.json` data file...

**Comment by adamrusted** [comment]
> I totally agree that would be a nicer solution, and I thought about it myself as well, but I can't think of a way to get this information currently (the file stats of the `npm install`ed SVGs does not contain the "real" last modified date) and I also don't think it makes sense to add a field for this to the `simple-icons.json` data file...

That's fair. I imagine otherwise there's a _LOT_ of logic to trying to find the commit that edited the file last, and using the timestamp of that commit. Not worth it in the grand scheme of things.

**Comment by ericcornelissen** [comment]
It's definitely _possible_, but not worth the trouble I'd say. Not to mention that it would require fetching the repository on top of/instead of fetching the package from NPM. 

I don't think that's worth the trouble of building and maintaining something for this here. Maybe we can do this if there's a pre-existing solution for analyzing the hit history like this 🤔

**Comment by adamrusted** [comment]
Yeah that's fair, as I say it's something for another PR if we decide to proceed with it. Happy for this to get merged in, if it's ready?

**Comment by ericcornelissen** [comment]
This PR is ready, but the website repo is not yet ready for this to be merged 🙃 hoping to get that done tomorrow.

**Comment by ericcornelissen** [comment]
> Yeah that's fair, as I say it's something for another PR if we decide to proceed with it.

Do you want to open an issue for that?

**Pull request merged**
